testFake:
    stage: test
    only:
        variables:
            - $JOB_NAME == "never use"
    script: 
        - echo "dont delete this stage! this is a pattern for your suite, copy and put your tests bellow" 

testSuite:
    stage: test
    only:
        variables:
            - $JOB_NAME == "suite"
    script: 
        - hwclock
        - dotnet test

testSuite2:
    stage: test
    only:
        variables:
            - $JOB_NAME == "suite2"
    script: 
        - hwclock
        - dotnet test

testSuite3:
    stage: test
    only:
        variables:
            - $JOB_NAME == "suite3"
    script: 
        - hwclock
        - dotnet test
        
testSuite4:
    stage: test
    only:
        variables:
            - $JOB_NAME == "suite4"
    script: 
        - hwclock
        - dotnet test
